
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          #https://github.com/nanasess/setup-chromedriver
        - uses: nanasess/setup-chromedriver@v1
        - run: |
            export DISPLAY=:99
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        - run: npm install
        - run: npm test